package com.cn.dg.mapper.system;

import com.cn.dg.bean.system.DgSysMenu;
import com.cn.dg.bean.system.DgSysMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DgSysMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dg_sys_menu
     *
     * @mbg.generated 2020-06-22
     */
    long countByExample(DgSysMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dg_sys_menu
     *
     * @mbg.generated 2020-06-22
     */
    int deleteByExample(DgSysMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dg_sys_menu
     *
     * @mbg.generated 2020-06-22
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dg_sys_menu
     *
     * @mbg.generated 2020-06-22
     */
    int insert(DgSysMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dg_sys_menu
     *
     * @mbg.generated 2020-06-22
     */
    int insertSelective(DgSysMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dg_sys_menu
     *
     * @mbg.generated 2020-06-22
     */
    List<DgSysMenu> selectByExample(DgSysMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dg_sys_menu
     *
     * @mbg.generated 2020-06-22
     */
    DgSysMenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dg_sys_menu
     *
     * @mbg.generated 2020-06-22
     */
    int updateByExampleSelective(@Param("record") DgSysMenu record, @Param("example") DgSysMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dg_sys_menu
     *
     * @mbg.generated 2020-06-22
     */
    int updateByExample(@Param("record") DgSysMenu record, @Param("example") DgSysMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dg_sys_menu
     *
     * @mbg.generated 2020-06-22
     */
    int updateByPrimaryKeySelective(DgSysMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dg_sys_menu
     *
     * @mbg.generated 2020-06-22
     */
    int updateByPrimaryKey(DgSysMenu record);
}