package com.cn.dg.mapper.system;

import com.cn.dg.bean.system.DgSysUser;
import com.cn.dg.bean.system.DgSysUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DgSysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dg_sys_user
     *
     * @mbg.generated 2020-06-22
     */
    long countByExample(DgSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dg_sys_user
     *
     * @mbg.generated 2020-06-22
     */
    int deleteByExample(DgSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dg_sys_user
     *
     * @mbg.generated 2020-06-22
     */
    int deleteByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dg_sys_user
     *
     * @mbg.generated 2020-06-22
     */
    int insert(DgSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dg_sys_user
     *
     * @mbg.generated 2020-06-22
     */
    int insertSelective(DgSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dg_sys_user
     *
     * @mbg.generated 2020-06-22
     */
    List<DgSysUser> selectByExample(DgSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dg_sys_user
     *
     * @mbg.generated 2020-06-22
     */
    DgSysUser selectByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dg_sys_user
     *
     * @mbg.generated 2020-06-22
     */
    int updateByExampleSelective(@Param("record") DgSysUser record, @Param("example") DgSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dg_sys_user
     *
     * @mbg.generated 2020-06-22
     */
    int updateByExample(@Param("record") DgSysUser record, @Param("example") DgSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dg_sys_user
     *
     * @mbg.generated 2020-06-22
     */
    int updateByPrimaryKeySelective(DgSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dg_sys_user
     *
     * @mbg.generated 2020-06-22
     */
    int updateByPrimaryKey(DgSysUser record);
}