package com.cn.dg.bean.system;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table dg_sys_user_role
 */
public class DgSysUserRole implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dg_sys_user_role.id
     *
     * @mbg.generated 2020-06-22
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dg_sys_user_role.userId
     *
     * @mbg.generated 2020-06-22
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dg_sys_user_role.roleId
     *
     * @mbg.generated 2020-06-22
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dg_sys_user_role
     *
     * @mbg.generated 2020-06-22
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dg_sys_user_role.id
     *
     * @return the value of dg_sys_user_role.id
     *
     * @mbg.generated 2020-06-22
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dg_sys_user_role.id
     *
     * @param id the value for dg_sys_user_role.id
     *
     * @mbg.generated 2020-06-22
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dg_sys_user_role.userId
     *
     * @return the value of dg_sys_user_role.userId
     *
     * @mbg.generated 2020-06-22
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dg_sys_user_role.userId
     *
     * @param userid the value for dg_sys_user_role.userId
     *
     * @mbg.generated 2020-06-22
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dg_sys_user_role.roleId
     *
     * @return the value of dg_sys_user_role.roleId
     *
     * @mbg.generated 2020-06-22
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dg_sys_user_role.roleId
     *
     * @param roleid the value for dg_sys_user_role.roleId
     *
     * @mbg.generated 2020-06-22
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dg_sys_user_role
     *
     * @mbg.generated 2020-06-22
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userid=").append(userid);
        sb.append(", roleid=").append(roleid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}