package com.cn.dg.bean.system;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table dg_sys_user
 */
public class DgSysUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dg_sys_user.userId
     *
     * @mbg.generated 2020-06-22
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dg_sys_user.createTime
     *
     * @mbg.generated 2020-06-22
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dg_sys_user.email
     *
     * @mbg.generated 2020-06-22
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dg_sys_user.expiredDate
     *
     * @mbg.generated 2020-06-22
     */
    private Date expireddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dg_sys_user.name
     *
     * @mbg.generated 2020-06-22
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dg_sys_user.password
     *
     * @mbg.generated 2020-06-22
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dg_sys_user.salt
     *
     * @mbg.generated 2020-06-22
     */
    private String salt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dg_sys_user.state
     *
     * @mbg.generated 2020-06-22
     */
    private Byte state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dg_sys_user.userName
     *
     * @mbg.generated 2020-06-22
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dg_sys_user
     *
     * @mbg.generated 2020-06-22
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dg_sys_user.userId
     *
     * @return the value of dg_sys_user.userId
     *
     * @mbg.generated 2020-06-22
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dg_sys_user.userId
     *
     * @param userid the value for dg_sys_user.userId
     *
     * @mbg.generated 2020-06-22
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dg_sys_user.createTime
     *
     * @return the value of dg_sys_user.createTime
     *
     * @mbg.generated 2020-06-22
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dg_sys_user.createTime
     *
     * @param createtime the value for dg_sys_user.createTime
     *
     * @mbg.generated 2020-06-22
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dg_sys_user.email
     *
     * @return the value of dg_sys_user.email
     *
     * @mbg.generated 2020-06-22
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dg_sys_user.email
     *
     * @param email the value for dg_sys_user.email
     *
     * @mbg.generated 2020-06-22
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dg_sys_user.expiredDate
     *
     * @return the value of dg_sys_user.expiredDate
     *
     * @mbg.generated 2020-06-22
     */
    public Date getExpireddate() {
        return expireddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dg_sys_user.expiredDate
     *
     * @param expireddate the value for dg_sys_user.expiredDate
     *
     * @mbg.generated 2020-06-22
     */
    public void setExpireddate(Date expireddate) {
        this.expireddate = expireddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dg_sys_user.name
     *
     * @return the value of dg_sys_user.name
     *
     * @mbg.generated 2020-06-22
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dg_sys_user.name
     *
     * @param name the value for dg_sys_user.name
     *
     * @mbg.generated 2020-06-22
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dg_sys_user.password
     *
     * @return the value of dg_sys_user.password
     *
     * @mbg.generated 2020-06-22
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dg_sys_user.password
     *
     * @param password the value for dg_sys_user.password
     *
     * @mbg.generated 2020-06-22
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dg_sys_user.salt
     *
     * @return the value of dg_sys_user.salt
     *
     * @mbg.generated 2020-06-22
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dg_sys_user.salt
     *
     * @param salt the value for dg_sys_user.salt
     *
     * @mbg.generated 2020-06-22
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dg_sys_user.state
     *
     * @return the value of dg_sys_user.state
     *
     * @mbg.generated 2020-06-22
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dg_sys_user.state
     *
     * @param state the value for dg_sys_user.state
     *
     * @mbg.generated 2020-06-22
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dg_sys_user.userName
     *
     * @return the value of dg_sys_user.userName
     *
     * @mbg.generated 2020-06-22
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dg_sys_user.userName
     *
     * @param username the value for dg_sys_user.userName
     *
     * @mbg.generated 2020-06-22
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dg_sys_user
     *
     * @mbg.generated 2020-06-22
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userid=").append(userid);
        sb.append(", createtime=").append(createtime);
        sb.append(", email=").append(email);
        sb.append(", expireddate=").append(expireddate);
        sb.append(", name=").append(name);
        sb.append(", password=").append(password);
        sb.append(", salt=").append(salt);
        sb.append(", state=").append(state);
        sb.append(", username=").append(username);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}