package com.cn.dg.bean.system;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table dg_sys_permission
 */
public class DgSysPermission implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dg_sys_permission.permissionId
     *
     * @mbg.generated 2020-06-20
     */
    private Integer permissionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dg_sys_permission.available
     *
     * @mbg.generated 2020-06-20
     */
    private Boolean available;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dg_sys_permission.parentId
     *
     * @mbg.generated 2020-06-20
     */
    private Long parentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dg_sys_permission.parentIds
     *
     * @mbg.generated 2020-06-20
     */
    private String parentids;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dg_sys_permission.permission
     *
     * @mbg.generated 2020-06-20
     */
    private String permission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dg_sys_permission.permissionName
     *
     * @mbg.generated 2020-06-20
     */
    private String permissionname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dg_sys_permission.resourceType
     *
     * @mbg.generated 2020-06-20
     */
    private String resourcetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dg_sys_permission.url
     *
     * @mbg.generated 2020-06-20
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dg_sys_permission
     *
     * @mbg.generated 2020-06-20
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dg_sys_permission.permissionId
     *
     * @return the value of dg_sys_permission.permissionId
     *
     * @mbg.generated 2020-06-20
     */
    public Integer getPermissionid() {
        return permissionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dg_sys_permission.permissionId
     *
     * @param permissionid the value for dg_sys_permission.permissionId
     *
     * @mbg.generated 2020-06-20
     */
    public void setPermissionid(Integer permissionid) {
        this.permissionid = permissionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dg_sys_permission.available
     *
     * @return the value of dg_sys_permission.available
     *
     * @mbg.generated 2020-06-20
     */
    public Boolean getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dg_sys_permission.available
     *
     * @param available the value for dg_sys_permission.available
     *
     * @mbg.generated 2020-06-20
     */
    public void setAvailable(Boolean available) {
        this.available = available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dg_sys_permission.parentId
     *
     * @return the value of dg_sys_permission.parentId
     *
     * @mbg.generated 2020-06-20
     */
    public Long getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dg_sys_permission.parentId
     *
     * @param parentid the value for dg_sys_permission.parentId
     *
     * @mbg.generated 2020-06-20
     */
    public void setParentid(Long parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dg_sys_permission.parentIds
     *
     * @return the value of dg_sys_permission.parentIds
     *
     * @mbg.generated 2020-06-20
     */
    public String getParentids() {
        return parentids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dg_sys_permission.parentIds
     *
     * @param parentids the value for dg_sys_permission.parentIds
     *
     * @mbg.generated 2020-06-20
     */
    public void setParentids(String parentids) {
        this.parentids = parentids == null ? null : parentids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dg_sys_permission.permission
     *
     * @return the value of dg_sys_permission.permission
     *
     * @mbg.generated 2020-06-20
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dg_sys_permission.permission
     *
     * @param permission the value for dg_sys_permission.permission
     *
     * @mbg.generated 2020-06-20
     */
    public void setPermission(String permission) {
        this.permission = permission == null ? null : permission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dg_sys_permission.permissionName
     *
     * @return the value of dg_sys_permission.permissionName
     *
     * @mbg.generated 2020-06-20
     */
    public String getPermissionname() {
        return permissionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dg_sys_permission.permissionName
     *
     * @param permissionname the value for dg_sys_permission.permissionName
     *
     * @mbg.generated 2020-06-20
     */
    public void setPermissionname(String permissionname) {
        this.permissionname = permissionname == null ? null : permissionname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dg_sys_permission.resourceType
     *
     * @return the value of dg_sys_permission.resourceType
     *
     * @mbg.generated 2020-06-20
     */
    public String getResourcetype() {
        return resourcetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dg_sys_permission.resourceType
     *
     * @param resourcetype the value for dg_sys_permission.resourceType
     *
     * @mbg.generated 2020-06-20
     */
    public void setResourcetype(String resourcetype) {
        this.resourcetype = resourcetype == null ? null : resourcetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dg_sys_permission.url
     *
     * @return the value of dg_sys_permission.url
     *
     * @mbg.generated 2020-06-20
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dg_sys_permission.url
     *
     * @param url the value for dg_sys_permission.url
     *
     * @mbg.generated 2020-06-20
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dg_sys_permission
     *
     * @mbg.generated 2020-06-20
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", permissionid=").append(permissionid);
        sb.append(", available=").append(available);
        sb.append(", parentid=").append(parentid);
        sb.append(", parentids=").append(parentids);
        sb.append(", permission=").append(permission);
        sb.append(", permissionname=").append(permissionname);
        sb.append(", resourcetype=").append(resourcetype);
        sb.append(", url=").append(url);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}