package com.cn.dg.bean.system;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table dg_sys_menu
 */
public class DgSysMenu implements Serializable {
    /**
     * Database Column Remarks:
     *   自增主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dg_sys_menu.id
     *
     * @mbg.generated 2020-06-20
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   父级主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dg_sys_menu.pid
     *
     * @mbg.generated 2020-06-20
     */
    private Integer pid;

    /**
     * Database Column Remarks:
     *   菜单名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dg_sys_menu.name
     *
     * @mbg.generated 2020-06-20
     */
    private String name;

    /**
     * Database Column Remarks:
     *   菜单地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dg_sys_menu.url
     *
     * @mbg.generated 2020-06-20
     */
    private String url;

    /**
     * Database Column Remarks:
     *   菜单类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dg_sys_menu.type
     *
     * @mbg.generated 2020-06-20
     */
    private String type;

    /**
     * Database Column Remarks:
     *   菜单状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dg_sys_menu.status
     *
     * @mbg.generated 2020-06-20
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dg_sys_menu
     *
     * @mbg.generated 2020-06-20
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dg_sys_menu.id
     *
     * @return the value of dg_sys_menu.id
     *
     * @mbg.generated 2020-06-20
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dg_sys_menu.id
     *
     * @param id the value for dg_sys_menu.id
     *
     * @mbg.generated 2020-06-20
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dg_sys_menu.pid
     *
     * @return the value of dg_sys_menu.pid
     *
     * @mbg.generated 2020-06-20
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dg_sys_menu.pid
     *
     * @param pid the value for dg_sys_menu.pid
     *
     * @mbg.generated 2020-06-20
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dg_sys_menu.name
     *
     * @return the value of dg_sys_menu.name
     *
     * @mbg.generated 2020-06-20
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dg_sys_menu.name
     *
     * @param name the value for dg_sys_menu.name
     *
     * @mbg.generated 2020-06-20
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dg_sys_menu.url
     *
     * @return the value of dg_sys_menu.url
     *
     * @mbg.generated 2020-06-20
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dg_sys_menu.url
     *
     * @param url the value for dg_sys_menu.url
     *
     * @mbg.generated 2020-06-20
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dg_sys_menu.type
     *
     * @return the value of dg_sys_menu.type
     *
     * @mbg.generated 2020-06-20
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dg_sys_menu.type
     *
     * @param type the value for dg_sys_menu.type
     *
     * @mbg.generated 2020-06-20
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dg_sys_menu.status
     *
     * @return the value of dg_sys_menu.status
     *
     * @mbg.generated 2020-06-20
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dg_sys_menu.status
     *
     * @param status the value for dg_sys_menu.status
     *
     * @mbg.generated 2020-06-20
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dg_sys_menu
     *
     * @mbg.generated 2020-06-20
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", pid=").append(pid);
        sb.append(", name=").append(name);
        sb.append(", url=").append(url);
        sb.append(", type=").append(type);
        sb.append(", status=").append(status);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}