package com.cn.dg.bean.system;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table dg_sys_role_permission
 */
public class DgSysRolePermission implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dg_sys_role_permission.id
     *
     * @mbg.generated 2020-06-20
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dg_sys_role_permission.permissionId
     *
     * @mbg.generated 2020-06-20
     */
    private Integer permissionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dg_sys_role_permission.roleId
     *
     * @mbg.generated 2020-06-20
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dg_sys_role_permission
     *
     * @mbg.generated 2020-06-20
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dg_sys_role_permission.id
     *
     * @return the value of dg_sys_role_permission.id
     *
     * @mbg.generated 2020-06-20
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dg_sys_role_permission.id
     *
     * @param id the value for dg_sys_role_permission.id
     *
     * @mbg.generated 2020-06-20
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dg_sys_role_permission.permissionId
     *
     * @return the value of dg_sys_role_permission.permissionId
     *
     * @mbg.generated 2020-06-20
     */
    public Integer getPermissionid() {
        return permissionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dg_sys_role_permission.permissionId
     *
     * @param permissionid the value for dg_sys_role_permission.permissionId
     *
     * @mbg.generated 2020-06-20
     */
    public void setPermissionid(Integer permissionid) {
        this.permissionid = permissionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dg_sys_role_permission.roleId
     *
     * @return the value of dg_sys_role_permission.roleId
     *
     * @mbg.generated 2020-06-20
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dg_sys_role_permission.roleId
     *
     * @param roleid the value for dg_sys_role_permission.roleId
     *
     * @mbg.generated 2020-06-20
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dg_sys_role_permission
     *
     * @mbg.generated 2020-06-20
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", permissionid=").append(permissionid);
        sb.append(", roleid=").append(roleid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}